server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true